name: medicore_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  dots_indicator: ^4.0.1
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  fading_edge_scrollview: ^4.1.1
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_datetime_picker_plus: ^2.2.0
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  flutter_timer_countdown: ^1.0.7
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  get_it: ^8.0.3
  go_router: ^15.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl_phone_field: ^3.2.0
  logger: ^2.5.0
  modal_progress_hud_nsn: ^0.5.1
  percent_indicator: ^4.2.5
  provider: ^6.1.5
  safe_network_image: ^1.0.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  table_calendar: ^3.2.0
  timeline_tile: ^2.0.0
  vibration: ^3.1.3
dependency_overrides:
  shared_preferences_android: 2.3.1

dev_dependencies:
  build_runner: ^2.5.1
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Icon.jpg"
  min_sdk_android: 21
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-Thin.ttf
          weight: 100
        - asset: fonts/RobotoSlab-Light.ttf
          weight: 300
        - asset: fonts/RobotoSlab-Regular.ttf
          weight: 400
        - asset: fonts/RobotoSlab-Medium.ttf
          weight: 500
        - asset: fonts/RobotoSlab-SemiBold.ttf
          weight: 600
        - asset: fonts/RobotoSlab-Bold.ttf
          weight: 700

    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Light.ttf
          weight: 300
        - asset: fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: fonts/Tajawal-Bold.ttf
          weight: 700

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_images.dart
  field_prefix: null
flutter_intl:
  enabled: true
