name: medicore_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  animations: ^2.0.11
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  dots_indicator: ^4.0.1
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.0
  flutter_timer_countdown: ^1.0.7
  get: ^4.7.2
  get_it: ^8.0.3
  intl_phone_field: ^3.2.0
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.5.3
  vibration: ^3.1.3
dependency_overrides:
  shared_preferences_android: 2.3.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Icon.jpg"
  min_sdk_android: 21
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-Thin.ttf
          weight: 100
        - asset: fonts/RobotoSlab-Light.ttf
          weight: 300
        - asset: fonts/RobotoSlab-Regular.ttf
          weight: 400
        - asset: fonts/RobotoSlab-Medium.ttf
          weight: 500
        - asset: fonts/RobotoSlab-SemiBold.ttf
          weight: 600
        - asset: fonts/RobotoSlab-Bold.ttf
          weight: 700

    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Light.ttf
          weight: 300
        - asset: fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: fonts/Tajawal-Bold.ttf
          weight: 700

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_images.dart
  field_prefix: null
flutter_intl:
  enabled: true
