// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBAtgllgMQLApd1dPms29KqCtn20U3cx0',
    appId: '1:827012261252:web:1cc227b90643982064e9d1',
    messagingSenderId: '827012261252',
    projectId: 'clinic-1f4bb',
    authDomain: 'clinic-1f4bb.firebaseapp.com',
    storageBucket: 'clinic-1f4bb.firebasestorage.app',
    measurementId: 'G-2QSJ81FWNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSw8lg_-9_A5R2gwBNVTpXMWhF1UnF378',
    appId: '1:827012261252:android:5d9dfda50fc9f28b64e9d1',
    messagingSenderId: '827012261252',
    projectId: 'clinic-1f4bb',
    storageBucket: 'clinic-1f4bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARERHnJyH4fN1p04AgKAHBtvvgu7BzZfY',
    appId: '1:827012261252:ios:50195730e662123564e9d1',
    messagingSenderId: '827012261252',
    projectId: 'clinic-1f4bb',
    storageBucket: 'clinic-1f4bb.firebasestorage.app',
    iosBundleId: 'com.example.medicoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARERHnJyH4fN1p04AgKAHBtvvgu7BzZfY',
    appId: '1:827012261252:ios:50195730e662123564e9d1',
    messagingSenderId: '827012261252',
    projectId: 'clinic-1f4bb',
    storageBucket: 'clinic-1f4bb.firebasestorage.app',
    iosBundleId: 'com.example.medicoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBAtgllgMQLApd1dPms29KqCtn20U3cx0',
    appId: '1:827012261252:web:616d4fb2c96bc50164e9d1',
    messagingSenderId: '827012261252',
    projectId: 'clinic-1f4bb',
    authDomain: 'clinic-1f4bb.firebaseapp.com',
    storageBucket: 'clinic-1f4bb.firebasestorage.app',
    measurementId: 'G-278QBPSMH0',
  );
}
